/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/clips": {
    /** Get Clips */
    get: operations["get_clips_clips_get"];
  };
  "/nearest_clip": {
    /** Get Nearest Clip */
    get: operations["get_nearest_clip_nearest_clip_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** RollingChatCount */
    RollingChatCount: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Count */
      count: number;
      /** Clip Id */
      clip_id: string | null;
      /** Rolling Sum */
      rolling_sum: number;
    };
    /** RollingChatCountWithThumbnail */
    RollingChatCountWithThumbnail: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Count */
      count: number;
      /** Clip Id */
      clip_id: string | null;
      /** Rolling Sum */
      rolling_sum: number;
      /** Thumbnail */
      thumbnail: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Clips */
  get_clips_clips_get: {
    parameters: {
      query?: {
        emote?: "classic" | "monka_giga" | "two" | "lol" | "cereal" | "monkas" | "joel" | "pog" | "huh" | "no" | "cocka" | "who_asked" | "shock" | "copium" | "ratjam" | "sure";
        span?: "day" | "week" | "month" | "all";
        sum_window?: "second" | "minute" | "week" | "day" | "month" | "all";
        order?: "asc" | "desc";
        limit?: number;
        cursor?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RollingChatCountWithThumbnail"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Nearest Clip */
  get_nearest_clip_nearest_clip_get: {
    parameters: {
      query: {
        epoch_time: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RollingChatCount"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
